const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';

const CHANGE_FILTER = 'CHANGE_FILTER';

export { ADD_TODO, DELETE_TODO, COMPLETE_TODO, CHANGE_FILTER };
